---
# ---所有节点都要做的操作----
- hosts: all
  remote_user: root
  gather_facts: True
  tasks:
  
  - name: 关闭selinux
    selinux: policy=targeted state=permissive
    selinux: state=disabled

# 提前准备好repo文件
  - name: 设置Base_repo
    copy: src=/root/repo/Centos-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  - name: 设置epel_repo
    copy: src=/root/repo/epel-7.repo dest=/etc/yum.repos.d/epel.repo
  - name: 设置MariaDB_repo
    copy: src=/root/repo/mariadb.repo dest=/etc/yum.repos.d/mariadb.repo

  - name: install firewalld
    yum: name=firewalld state=present

  - name: sotp firewalld
    service: name=firewalld state=stopped enabled=no

  - name: 安装MariaDB-server galera
    yum: name={{ item }} enablerepo=mariadb state=present
    with_items:
    - MariaDB-server
    - galera


# ---第一个启动的节点要做的操作---
- hosts: master
  remote_user: root
  gather_facts: True
  tasks:
  - name: 复制配置文件
    template: src=/root/config/master.j2 dest=/etc/my.cnf.d/server.cnf
  - name: 启动地一个节点
    shell: galera_new_cluster

# ---其他的节点要做的操作，配置文件中，先把各个节点的IP地址列表写进去，自己的IP地址可以不用写，已经自己获取---
- hosts: others
  remote_user: root
  gather_facts: True
  tasks:
  - name: 复制配置文件
    template: src=/root/config/others.j2 dest=/etc/my.cnf.d/server.cnf
  - name: 启动其他节点
    service: name=mariadb state=started
                                                                                                         
