---
- hosts: all
  remote_user: root
  gather_facts: True
  tasks:
  - name: disabled selinux
    selinux: policy=targeted state=permissive
    selinux: state=disabled

  - name: 屏蔽掉系统原有repo
    shell: mkdir /etc/yum.repos.d/back && mv /etc/yum.repos.d/C* /etc/yum.repos.d/back || echo '重复'

  - name: 设置Base_repo
    copy: src=/root/repo/Centos-7.repo dest=/etc/yum.repos.d/CentOS-Base.repo
  - name: 设置epel_repo
    copy: src=/root/repo/epel-7.repo dest=/etc/yum.repos.d/epel.repo
  - name: 设置MariaDB_repo
    copy: src=/root/repo/mariadb.repo dest=/etc/yum.repos.d/mariadb.repo

  - name: install firewalld
    yum: name=firewalld state=present

  - name: sotp firewalld
    service: name=firewalld state=stopped enabled=no

  - name: 安装MariaDB-server galera
    yum: name={{ item }} enablerepo=mariadb10 state=present
    with_items:
    - MariaDB-server
    - galera

  - name: 复制配置文件
    template: src=/root/config/server10.j2 dest=/etc/my.cnf.d/server.cnf

- hosts: master
  remote_user: root
  gather_facts: True
  tasks:
  - name: 启动地一个节点
    shell: galera_new_cluster

- hosts: others
  remote_user: root
  gather_facts: True
  tasks:
  - name: 启动其他节点
    service: name=mariadb state=started
    
    
配置文件
[galera]
# Mandatory settings
wsrep_on=ON
wsrep_provider=/usr/lib64/galera/libgalera_smm.so
# specify all nodes in cluster(所有节点的IP)
wsrep_cluster_address=gcomm://{% for i in groups['all'] %}{{i}}{% if loop.last %}{% else %},{% endif %} {% endfor %}
binlog_format=row
default_storage_engine=InnoDB
innodb_autoinc_lock_mode=2
bind-address=0.0.0.0

# add follows
# cluster name
wsrep_cluster_name="MariaDB_Cluster"
# own IP address（当前节点的IP）
wsrep_node_address={{ ansible_all_ipv4_addresses[0] }}
# replication provider
wsrep_sst_method=rsync

 
